name: deploy

on:
  workflow_dispatch:
    inputs:
      targetJob:
        description: 'Target job to run'
        required: true
        options:
          - multistage-copy-nocache
          - multistage-copy-layercache-gha
          - multistage-copy-layercache-local
          - multistage-mount-layercache-gha
          - multistage-mount-layercache-gocache-gha
          - multistage-mount-gocache
          - multistage-mount-gocache-warashi

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  multistage-copy-nocache:
    runs-on: ubuntu-latest
    if: github.event.inputs.targetJob == 'multistage-copy-nocache'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: multistage-copy.Dockerfile
          push: false
          platforms: linux/amd64
          provenance: false
  multistage-copy-layercache-gha:
    runs-on: ubuntu-latest
    if: github.event.inputs.targetJob == 'multistage-copy-layercache-gha'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: multistage-copy.Dockerfile
          push: false
          platforms: linux/amd64
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
  multistage-copy-layercache-local:
    runs-on: ubuntu-latest
    if: github.event.inputs.targetJob == 'multistage-copy-layercache-local'
    steps:
      - uses: actions/checkout@v4
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: multistage-copy.Dockerfile
          push: false
          platforms: linux/amd64
          provenance: false
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  multistage-mount-layercache-gha:
    runs-on: ubuntu-latest
    if: github.event.inputs.targetJob == 'multistage-mount-layercache-gha'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: multistage-mount.Dockerfile
          push: false
          platforms: linux/amd64
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
  multistage-mount-layercache-gocache-gha:
    runs-on: ubuntu-latest
    if: github.event.inputs.targetJob == 'multistage-mount-layercache-gocache-gha'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: actions/cache@v4
        with:
          path: |
            go-mod-cache
            go-build-cache
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: reproducible-containers/buildkit-cache-dance@v3.1.2
        with:
          cache-map: |
            {
              "go-mod-cache": "/go/pkg/mod",
              "go-build-cache": "/root/.cache/go-build"
            }
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: multistage-mount.Dockerfile
          push: false
          platforms: linux/amd64
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
  multistage-mount-gocache:
    runs-on: ubuntu-latest
    if: github.event.inputs.targetJob == 'multistage-mount-gocache'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: actions/cache@v4
        with:
          path: |
            go-mod-cache
            go-build-cache
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: reproducible-containers/buildkit-cache-dance@v3.1.2
        with:
          cache-map: |
            {
              "go-mod-cache": "/go/pkg/mod",
              "go-build-cache": "/root/.cache/go-build"
            }
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: multistage-mount.Dockerfile
          push: false
          platforms: linux/amd64
          provenance: false
  multistage-mount-gocache-warashi:
    runs-on: ubuntu-latest
    if: github.event.inputs.targetJob == 'multistage-mount-gocache-warashi'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        id: setup-buildx
      - uses: actions/cache@v4
        with:
          path: |
            go-mod-cache
            go-build-cache
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: Warashi/buildkit-cache-dance@a9b89166be6bf8c298db64c1bc3c5881ec7afd9d # compress-and-use-output
        with:
          builder: ${{ steps.setup-buildx.outputs.name }}
          cache-map: |
            {
              "go-mod-cache": "/go/pkg/mod",
              "go-build-cache": "/root/.cache/go-build"
            }
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: multistage-mount.Dockerfile
          push: false
          platforms: linux/amd64
          provenance: false
